name: ChequePlugin
version: 1.0.0
main: ChequePlugin\Main
api: 3.28.0
description: Plugin para criar e resgatar cheques em uma UI.
author: duzzmoney
depend: 
  - EconomyAPI
commands:
  cheque:
    description: Abre a interface para criar um cheque.
    usage: /cheque
permissions:
  cheque.create:
    description: Permissão para criar cheques.
    default: true
  cheque.use:
    description: Permissão para usar cheques.
    default: true
    
